#!/bin/bash
# Test addons with logfile to /var/log/odoo
odoo -d db -u $1 --test-enable --test-report-directory=/var/log/odoo --log-level=test --db_host db --db_port 5432 --db_user odoo --db_password odoo --xmlrpc-port=8069 --stop-after-init
